use_frameworks!

target 'XBaseStorage_Example' do
  pod 'XBaseStorage', :path => '../'
  pod 'RealmSwift'

  target 'XBaseStorage_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
